

// // import axios from "axios";
// // import NavBar from "../components/NavBar";
// // import Footer from "../components/Footer";
// // import React, { useState, useEffect } from "react";
// // import { Camera } from "lucide-react";
// // import { Input } from "./input";
// // import { Button } from "./button";
// // import { Card, CardHeader, CardContent } from "./card";
// // import { Alert, AlertDescription } from "./alert";

// // const PersonalProfilePage = () => {
// //   const [profilePic, setProfilePic] = useState("/api/placeholder/150/150");
// //   const [username, setUsername] = useState("");
// //   const [password, setPassword] = useState("");
// //   const [email, setEmail] = useState("");
// //   const [showAlert, setShowAlert] = useState(false);
// //   const [customerId, setCustomerId] = useState(null);

// //   useEffect(() => {
// //     const id = sessionStorage.getItem("customerId");
// //     if (id) {
// //       setCustomerId(id);
// //       axios
// //         .get(
// //           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${id}.json`
// //         )
// //         .then((response) => {
// //           const customer = response.data;
// //           if (customer) {
// //             setUsername(customer.name || "");
// //             setPassword(customer.password || "");
// //             setEmail(customer.email || "");
// //             setProfilePic(customer.profileImage || "/api/placeholder/150/150");
// //           }
// //         })
// //         .catch((error) => {
// //           console.error("Error fetching customer data:", error);
// //         });
// //     }
// //   }, []);

// //   const handleProfilePicChange = (e) => {
// //     const file = e.target.files[0];
// //     if (file) {
// //       const reader = new FileReader();
// //       reader.onloadend = () => {
// //         // Use the URL generated by FileReader to set as profile picture
// //         setProfilePic(reader.result);
// //       };
// //       reader.readAsDataURL(file);
// //     }
// //   };

// //   const handleSave = () => {
// //     if (customerId) {
// //       const updatedCustomer = {
// //         name: username,
// //         password: password,
// //         email: email,
// //         profileImage: profilePic,
// //       };

// //       axios
// //         .patch(
// //           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${customerId}.json`,
// //           updatedCustomer
// //         )
// //         .then(() => {
// //           setShowAlert(true);
// //           setTimeout(() => setShowAlert(false), 3000);
// //         })
// //         .catch((error) => {
// //           console.error("Error updating customer data:", error);
// //         });
// //     }
// //   };

// //   return (
// //     <>
// //       <NavBar />
// //       <div className="container mx-auto px-4 py-8 mt-16">
// //         <div className="flex justify-center">
// //           <Card className="w-full max-w-lg p-6 shadow-lg ">
// //             <CardHeader>
// //               <h2 className="text-3xl font-bold text-center text-gray-800">
// //                 Personal Profile
// //               </h2>
// //             </CardHeader>
// //             <CardContent>
// //               <div className="flex flex-col items-center mb-4">
// //                 <div className="relative">
// //                   <img
// //                     src={profilePic}
// //                     alt="Profile"
// //                     className="w-32 h-32 rounded-full object-cover mb-4 shadow-md"
// //                   />
// //                   <label
// //                     htmlFor="profile-pic-input"
// //                     className="absolute bottom-0 right-0 bg-gray-200 rounded-full p-2 cursor-pointer shadow-md hover:bg-gray-300 transition-colors"
// //                   >
// //                     <Camera size={24} className="text-gray-600" />
// //                   </label>
// //                   <input
// //                     id="profile-pic-input"
// //                     type="file"
// //                     accept="image/*"
// //                     onChange={handleProfilePicChange}
// //                     className="hidden"
// //                   />
// //                 </div>
// //               </div>
// //               <div className="space-y-4">
// //                 <div>
// //                   <label
// //                     htmlFor="username"
// //                     className="block text-sm font-medium text-gray-700"
// //                   >
// //                     Username
// //                   </label>
// //                   <Input
// //                     id="username"
// //                     type="text"
// //                     value={username}
// //                     onChange={(e) => setUsername(e.target.value)}
// //                     placeholder="Enter your username"
// //                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
// //                   />
// //                 </div>
// //                 <div>
// //                   <label
// //                     htmlFor="password"
// //                     className="block text-sm font-medium text-gray-700"
// //                   >
// //                     Password
// //                   </label>
// //                   <Input
// //                     id="password"
// //                     type="password"
// //                     value={password}
// //                     onChange={(e) => setPassword(e.target.value)}
// //                     placeholder="Enter your password"
// //                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
// //                   />
// //                 </div>
// //                 <div>
// //                   <label
// //                     htmlFor="email"
// //                     className="block text-sm font-medium text-gray-700"
// //                   >
// //                     Email
// //                   </label>
// //                   <Input
// //                     id="email"
// //                     type="email"
// //                     value={email}
// //                     onChange={(e) => setEmail(e.target.value)}
// //                     placeholder="Enter your email"
// //                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
// //                   />
// //                 </div>
// //                 <Button
// //                   onClick={handleSave}
// //                   className="w-full bg-indigo-500 text-white py-2 rounded-md hover:bg-indigo-600 transition-colors"
// //                 >
// //                   Save
// //                 </Button>
// //                 {showAlert && (
// //                   <Alert variant="success" className="mt-4">
// //                     <AlertDescription>
// //                       Data has been saved successfully!
// //                     </AlertDescription>
// //                   </Alert>
// //                 )}
// //               </div>
// //             </CardContent>
// //           </Card>
// //         </div>
// //       </div>
// //       <Footer />
// //     </>
// //   );
// // };

// // export default PersonalProfilePage;



// import axios from "axios";
// import NavBar from "../components/NavBar";
// import Footer from "../components/Footer";
// import React, { useState, useEffect } from "react";
// import { Camera } from "lucide-react";
// import { Input } from "./input";
// import { Button } from "./button";
// import { Card, CardHeader, CardContent } from "./card";
// import { Alert, AlertDescription } from "./alert";

// const PersonalProfilePage = () => {
//   const [profilePic, setProfilePic] = useState("/api/placeholder/150/150");
//   const [username, setUsername] = useState("");
//   const [password, setPassword] = useState("");
//   const [email, setEmail] = useState("");
//   const [showAlert, setShowAlert] = useState(false);
//   const [customerId, setCustomerId] = useState(null);

//   useEffect(() => {
//     const id = sessionStorage.getItem("customerId");
//     if (id) {
//       setCustomerId(id);
//       axios
//         .get(
//           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${id}.json`
//         )
//         .then((response) => {
//           const customer = response.data;
//           if (customer) {
//             setUsername(customer.name || "");
//             setPassword(customer.password || "");
//             setEmail(customer.email || "");
//             setProfilePic(customer.profileImage || "/api/placeholder/150/150");
//           }
//         })
//         .catch((error) => {
//           console.error("Error fetching customer data:", error);
//         });
//     }
//   }, []);

//   const handleProfilePicChange = (e) => {
//     const file = e.target.files[0];
//     if (file) {
//       const reader = new FileReader();
//       reader.onloadend = () => {
//         setProfilePic(reader.result);
//       };
//       reader.readAsDataURL(file);
//     }
//   };

//   const handleSave = () => {
//     if (customerId) {
//       const updatedCustomer = {
//         name: username,
//         password: password,
//         email: email,
//         profileImage: profilePic,
//       };

//       axios
//         .patch(
//           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${customerId}.json`,
//           updatedCustomer
//         )
//         .then(() => {
//           setShowAlert(true);
//           setTimeout(() => setShowAlert(false), 3000);
//         })
//         .catch((error) => {
//           console.error("Error updating customer data:", error);
//         });
//     }
//   };

//   return (
//     <>
//       <NavBar />
//       <div className="container mx-auto px-4 py-8 mt-16">
//         <div className="flex justify-center">
//           <Card className="w-full max-w-lg p-6 shadow-lg bg-white rounded-lg">
//             <CardHeader>
//               <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800">
//                 Personal Profile
//               </h2>
//             </CardHeader>
//             <CardContent>
//               <div className="flex flex-col items-center mb-6">
//                 <div className="relative">
//                   <img
//                     src={profilePic}
//                     alt="Profile"
//                     className="w-24 h-24 md:w-32 md:h-32 rounded-full object-cover mb-4 shadow-md"
//                   />
//                   <label
//                     htmlFor="profile-pic-input"
//                     className="absolute bottom-0 right-0 bg-gray-200 rounded-full p-2 cursor-pointer shadow-md hover:bg-gray-300 transition-colors"
//                   >
//                     <Camera size={24} className="text-gray-600" />
//                   </label>
//                   <input
//                     id="profile-pic-input"
//                     type="file"
//                     accept="image/*"
//                     onChange={handleProfilePicChange}
//                     className="hidden"
//                   />
//                 </div>
//               </div>
//               <div className="space-y-4">
//                 <div>
//                   <label
//                     htmlFor="username"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Username
//                   </label>
//                   <Input
//                     id="username"
//                     type="text"
//                     value={username}
//                     onChange={(e) => setUsername(e.target.value)}
//                     placeholder="Enter your username"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <div>
//                   <label
//                     htmlFor="password"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Password
//                   </label>
//                   <Input
//                     id="password"
//                     type="password"
//                     value={password}
//                     onChange={(e) => setPassword(e.target.value)}
//                     placeholder="Enter your password"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <div>
//                   <label
//                     htmlFor="email"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Email
//                   </label>
//                   <Input
//                     id="email"
//                     type="email"
//                     value={email}
//                     onChange={(e) => setEmail(e.target.value)}
//                     placeholder="Enter your email"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <Button
//                   onClick={handleSave}
//                   className="w-full bg-indigo-500 text-white py-2 rounded-md hover:bg-indigo-600 transition-colors"
//                 >
//                   Save
//                 </Button>
//                 {showAlert && (
//                   <Alert variant="success" className="mt-4">
//                     <AlertDescription>
//                       Data has been saved successfully!
//                     </AlertDescription>
//                   </Alert>
//                 )}
//               </div>
//             </CardContent>
//           </Card>
//         </div>
//       </div>
//       <Footer />
//     </>
//   );
// };

// export default PersonalProfilePage;


// import axios from "axios";
// import NavBar from "../components/NavBar";
// import Footer from "../components/Footer";
// import React, { useState, useEffect } from "react";
// import { Camera } from "lucide-react";
// import { Input } from "./input";
// import { Button } from "./button";
// import { Card, CardHeader, CardContent } from "./card";
// import { Alert, AlertDescription } from "./alert";

// const PersonalProfilePage = () => {
//   const [profilePic, setProfilePic] = useState("/api/placeholder/150/150");
//   const [username, setUsername] = useState("");
//   const [password, setPassword] = useState("");
//   const [email, setEmail] = useState("");
//   const [showAlert, setShowAlert] = useState(false);
//   const [customerId, setCustomerId] = useState(null);
//   const [orders, setOrders] = useState([]);

//   useEffect(() => {
//     const id = sessionStorage.getItem("customerId");
//     if (id) {
//       setCustomerId(id);
//       axios
//         .get(
//           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${id}.json`
//         )
//         .then((response) => {
//           const customer = response.data;
//           if (customer) {
//             setUsername(customer.name || "");
//             setPassword(customer.password || "");
//             setEmail(customer.email || "");
//             setProfilePic(customer.profileImage || "/api/placeholder/150/150");
//           }
//         })
//         .catch((error) => {
//           console.error("Error fetching customer data:", error);
//         });

//       // Fetch orders from session storage
//       const storedOrders = sessionStorage.getItem("orderDetails");
//       if (storedOrders) {
//         const parsedOrders = JSON.parse(storedOrders);
//         setOrders([parsedOrders]); // Assuming only one order object for simplicity
//       }
//     }
//   }, []);

//   const handleProfilePicChange = (e) => {
//     const file = e.target.files[0];
//     if (file) {
//       const reader = new FileReader();
//       reader.onloadend = () => {
//         setProfilePic(reader.result);
//       };
//       reader.readAsDataURL(file);
//     }
//   };

//   const handleSave = () => {
//     if (customerId) {
//       const updatedCustomer = {
//         name: username,
//         password: password,
//         email: email,
//         profileImage: profilePic,
//       };

//       axios
//         .patch(
//           `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${customerId}.json`,
//           updatedCustomer
//         )
//         .then(() => {
//           setShowAlert(true);
//           setTimeout(() => setShowAlert(false), 3000);
//         })
//         .catch((error) => {
//           console.error("Error updating customer data:", error);
//         });
//     }
//   };

//   return (
//     <>
//       <NavBar />
//       <div className="container mx-auto px-4 py-8 mt-16">
//         <div className="flex flex-col items-center">
//           <Card className="w-full max-w-lg p-6 shadow-lg bg-white rounded-lg mb-8">
//             <CardHeader>
//               <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800">
//                 Personal Profile
//               </h2>
//             </CardHeader>
//             <CardContent>
//               <div className="flex flex-col items-center mb-6">
//                 <div className="relative">
//                   <img
//                     src={profilePic}
//                     alt="Profile"
//                     className="w-24 h-24 md:w-32 md:h-32 rounded-full object-cover mb-4 shadow-md"
//                   />
//                   <label
//                     htmlFor="profile-pic-input"
//                     className="absolute bottom-0 right-0 bg-gray-200 rounded-full p-2 cursor-pointer shadow-md hover:bg-gray-300 transition-colors"
//                   >
//                     <Camera size={24} className="text-gray-600" />
//                   </label>
//                   <input
//                     id="profile-pic-input"
//                     type="file"
//                     accept="image/*"
//                     onChange={handleProfilePicChange}
//                     className="hidden"
//                   />
//                 </div>
//               </div>
//               <div className="space-y-4">
//                 <div>
//                   <label
//                     htmlFor="username"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Username
//                   </label>
//                   <Input
//                     id="username"
//                     type="text"
//                     value={username}
//                     onChange={(e) => setUsername(e.target.value)}
//                     placeholder="Enter your username"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <div>
//                   <label
//                     htmlFor="password"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Password
//                   </label>
//                   <Input
//                     id="password"
//                     type="password"
//                     value={password}
//                     onChange={(e) => setPassword(e.target.value)}
//                     placeholder="Enter your password"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <div>
//                   <label
//                     htmlFor="email"
//                     className="block text-sm font-medium text-gray-700"
//                   >
//                     Email
//                   </label>
//                   <Input
//                     id="email"
//                     type="email"
//                     value={email}
//                     onChange={(e) => setEmail(e.target.value)}
//                     placeholder="Enter your email"
//                     className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
//                   />
//                 </div>
//                 <Button
//                   onClick={handleSave}
//                   className="w-full bg-indigo-500 text-white py-2 rounded-md hover:bg-indigo-600 transition-colors"
//                 >
//                   Save
//                 </Button>
//                 {showAlert && (
//                   <Alert variant="success" className="mt-4">
//                     <AlertDescription>
//                       Data has been saved successfully!
//                     </AlertDescription>
//                   </Alert>
//                 )}
//               </div>
//             </CardContent>
//           </Card>

//           {/* Orders Section */}
//           <Card className="w-full max-w-lg p-6 shadow-lg bg-white rounded-lg">
//             <CardHeader>
//               <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800">
//                 Your Orders
//               </h2>
//             </CardHeader>
//             <CardContent>
//               {orders.length === 0 ? (
//                 <p className="text-center text-gray-600">No orders found.</p>
//               ) : (
//                 <div>
//                   {orders.map((order, index) => (
//                     <div key={index} className="border-b border-gray-200 pb-4 mb-4">
//                       <h3 className="text-lg font-semibold text-gray-800">Order #{index + 1}</h3>
//                       <p className="text-gray-600">Subtotal: ${order.subtotal}</p>
//                       <p className="text-gray-600">Tax: ${order.tax}</p>
//                       <p className="text-gray-600">Total: ${order.total}</p>
//                       <p className="text-gray-600">Payment Method: {order.paymentMethod}</p>
//                       <p className="text-gray-600">Coupon Code: {order.couponCode || 'None'}</p>
//                       <h4 className="text-md font-semibold text-gray-800 mt-2">Items:</h4>
//                       <ul className="list-disc pl-5">
//                         {order.items.map((item, idx) => (
//                           <li key={idx} className="text-gray-600">
//                             {item.name} x {item.quantity}
//                           </li>
//                         ))}
//                       </ul>
//                       <p className="text-gray-600 mt-2">Card Info: {order.cardInfo.cardNumber ? 'Provided' : 'Not Provided'}</p>
//                     </div>
//                   ))}
//                 </div>
//               )}
//             </CardContent>
//           </Card>
//         </div>
//       </div>
//       <Footer />
//     </>
//   );
// };

// export default PersonalProfilePage;


import axios from "axios";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import React, { useState, useEffect } from "react";
import { Camera } from "lucide-react";
import { Input } from "./input";
import { Button } from "./button";
import { Card, CardHeader, CardContent } from "./card";
import { Alert, AlertDescription } from "./alert";

const PersonalProfilePage = () => {
  const [profilePic, setProfilePic] = useState("/api/placeholder/150/150");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [email, setEmail] = useState("");
  const [showAlert, setShowAlert] = useState(false);
  const [customerId, setCustomerId] = useState(null);
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    const id = sessionStorage.getItem("customerId");
    if (id) {
      setCustomerId(id);
      axios
        .get(
          `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${id}.json`
        )
        .then((response) => {
          const customer = response.data;
          if (customer) {
            setUsername(customer.name || "");
            setPassword(customer.password || "");
            setEmail(customer.email || "");
            setProfilePic(customer.profileImage || "/api/placeholder/150/150");
          }
        })
        .catch((error) => {
          console.error("Error fetching customer data:", error);
        });

      // Fetch orders from session storage
      const storedOrders = sessionStorage.getItem("orderDetails");
      if (storedOrders) {
        try {
          const parsedOrders = JSON.parse(storedOrders);
          setOrders([parsedOrders]); // Assuming only one order object for simplicity
        } catch (error) {
          console.error("Error parsing orders from session storage:", error);
        }
      }
    }
  }, []);

  const handleProfilePicChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setProfilePic(reader.result);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSave = () => {
    if (customerId) {
      const updatedCustomer = {
        name: username,
        password: password,
        email: email,
        profileImage: profilePic,
      };

      axios
        .patch(
          `https://culture-3-default-rtdb.europe-west1.firebasedatabase.app/users/customers/${customerId}.json`,
          updatedCustomer
        )
        .then(() => {
          setShowAlert(true);
          setTimeout(() => setShowAlert(false), 3000);
        })
        .catch((error) => {
          console.error("Error updating customer data:", error);
        });
    }
  };

  return (
    <>
      <NavBar />
      <div className="container mx-auto px-4 py-8 mt-16">
        <div className="flex flex-col items-center">
          <Card className="w-full max-w-lg p-6 shadow-lg bg-white rounded-lg mb-8">
            <CardHeader>
              <h2 className="text-2xl md:text-3xl font-bold text-center text-red1">
                Personal Profile
              </h2>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col items-center mb-6">
                <div className="relative">
                  <img
                    src={profilePic}
                    alt="Profile"
                    className="w-24 h-24 md:w-32 md:h-32 rounded-full object-cover mb-4 shadow-md"
                  />
                  <label
                    htmlFor="profile-pic-input"
                    className="absolute bottom-0 right-0 bg-gray-200 rounded-full p-2 cursor-pointer shadow-md hover:bg-gray-300 transition-colors"
                  >
                    <Camera size={24} className="text-gray-600" />
                  </label>
                  <input
                    id="profile-pic-input"
                    type="file"
                    accept="image/*"
                    onChange={handleProfilePicChange}
                    className="hidden"
                  />
                </div>
              </div>
              <div className="space-y-4">
                <div>
                  <label
                    htmlFor="username"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Username
                  </label>
                  <Input
                    id="username"
                    type="text"
                    value={username}
                    onChange={(e) => setUsername(e.target.value)}
                    placeholder="Enter your username"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label
                    htmlFor="password"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Password
                  </label>
                  <Input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Enter your password"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label
                    htmlFor="email"
                    className="block text-sm font-medium text-gray-700"
                  >
                    Email
                  </label>
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Enter your email"
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
                  />
                </div>
                <Button
                  onClick={handleSave}
                  className="w-full bg-red1 text-white py-2 rounded-md hover:bg-red2 transition-colors"
                >
                  Save
                </Button>
                {showAlert && (
                  <Alert variant="success" className="mt-4">
                    <AlertDescription>
                      Data has been saved successfully!
                    </AlertDescription>
                  </Alert>
                )}
              </div>
            </CardContent>
          </Card>

          {/* Orders Section */}
          <Card className="w-full max-w-lg p-6 shadow-lg bg-white rounded-lg">
            <CardHeader>
              <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-800">
                Your Orders
              </h2>
            </CardHeader>
            <CardContent>
              {orders.length === 0 ? (
                <p className="text-center text-gray-600">No orders found.</p>
              ) : (
                <div>
                  {orders.map((order, index) => (
                    <div key={index} className="border-b border-gray-200 pb-4 mb-4">
                      <h3 className="text-lg font-semibold text-gray-800">Order #{index + 1}</h3>
                      <p className="text-gray-600">Subtotal: ${order.subtotal}</p>
                      <p className="text-gray-600">Tax: ${order.tax}</p>
                      <p className="text-gray-600">Total: ${order.total}</p>
                      <p className="text-gray-600">Payment Method: {order.paymentMethod}</p>
                      <p className="text-gray-600">Coupon Code: {order.couponCode || 'None'}</p>
                      <h4 className="text-md font-semibold text-gray-800 mt-2">Items:</h4>
                      <ul className="list-disc pl-5">
                        {order.items.map((item, idx) => (
                          <li key={idx} className="text-gray-600">
                            {item.name} x {item.quantity}
                          </li>
                        ))}
                      </ul>
                      <p className="text-gray-600 mt-2">Card Info: {order.cardInfo?.cardNumber ? 'Provided' : 'Not Provided'}</p>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PersonalProfilePage;
